insert into Restaurants (rid, name, address, min_amt_threshold) values (1, 'Pizza World', '86486 Melrose Street', 14);
insert into Restaurants (rid, name, address, min_amt_threshold) values (2, 'Chocolate Land', '40 Independence Terrace', 13);
insert into Restaurants (rid, name, address, min_amt_threshold) values (3, 'Chicken Corner', '7304 Gale Trail', 24);
insert into Restaurants (rid, name, address, min_amt_threshold) values (4, 'Fish Delights', '46 Spohn Junction', 20);
insert into Restaurants (rid, name, address, min_amt_threshold) values (5, 'Tavern Place', '8342 Mitchell Parkway', 14);
insert into Restaurants (rid, name, address, min_amt_threshold) values (6, 'Indian Delights', '733 Main Junction', 22);
insert into Restaurants (rid, name, address, min_amt_threshold) values (7, 'Pizza Hut', '65205 Manufacturers Terrace', 20);
insert into Restaurants (rid, name, address, min_amt_threshold) values (8, 'KFC', '8371 Granby Circle', 12);
insert into Restaurants (rid, name, address, min_amt_threshold) values (9, 'Foodie Paradise', '39 Anhalt Pass', 28);
insert into Restaurants (rid, name, address, min_amt_threshold) values (10, 'Chinese World', '110 Montana Way', 10);
insert into Restaurants (rid, name, address, min_amt_threshold) values (11, 'Gourmet Land', '6 Monument Circle', 14);
insert into Restaurants (rid, name, address, min_amt_threshold) values (12, 'Lim Eatery', '58 Mayer Junction', 16);
insert into Restaurants (rid, name, address, min_amt_threshold) values (13, 'Koi', '9929 School Parkway', 22);
insert into Restaurants (rid, name, address, min_amt_threshold) values (14, 'Llao Llao', '8 Lakeland Court', 12);
insert into Restaurants (rid, name, address, min_amt_threshold) values (15, 'MacDonalds', '9051 Golden Leaf Way', 20);
insert into Restaurants (rid, name, address, min_amt_threshold) values (16, 'Wendys', '7 Shasta Court', 28);
insert into Restaurants (rid, name, address, min_amt_threshold) values (17, 'Fried Chicken Specials', '85 Springs Drive', 17);
insert into Restaurants (rid, name, address, min_amt_threshold) values (18, 'Arnolds', '9460 Maple Wood Crossing', 16);
insert into Restaurants (rid, name, address, min_amt_threshold) values (19, 'Canton Paradise', '34 Dakota Terrace', 11);
insert into Restaurants (rid, name, address, min_amt_threshold) values (20, 'Dian Xiao Er', '36228 Golf Course Avenue', 10);
insert into Restaurants (rid, name, address, min_amt_threshold) values (21, 'FoodKing', '59686 Rutledge Terrace', 24);
insert into Restaurants (rid, name, address, min_amt_threshold) values (22, 'Pizza Place', '11904 Pleasure Pass', 28);
insert into Restaurants (rid, name, address, min_amt_threshold) values (23, 'Corleone Corner', '015 Thompson Crossing', 24);
insert into Restaurants (rid, name, address, min_amt_threshold) values (24, 'Hainan Chicken', '84674 Alpine Alley', 15);
insert into Restaurants (rid, name, address, min_amt_threshold) values (25, 'Laksa Mama', '9 Crownhardt Terrace', 23);
