insert into Restaurants (name, address, min_amt_threshold) values ('Pizza World', '86486 Melrose Street', 14);
insert into Restaurants (name, address, min_amt_threshold) values ('Chocolate Land', '40 Independence Terrace', 13);
insert into Restaurants (name, address, min_amt_threshold) values ('Chicken Corner', '7304 Gale Trail', 24);
insert into Restaurants (name, address, min_amt_threshold) values ('Fish Delights', '46 Spohn Junction', 20);
insert into Restaurants (name, address, min_amt_threshold) values ('Tavern Place', '8342 Mitchell Parkway', 14);
insert into Restaurants (name, address, min_amt_threshold) values ('Indian Delights', '733 Main Junction', 22);
insert into Restaurants (name, address, min_amt_threshold) values ('Pizza Hut', '65205 Manufacturers Terrace', 20);
insert into Restaurants (name, address, min_amt_threshold) values ('KFC', '8371 Granby Circle', 12);
insert into Restaurants (name, address, min_amt_threshold) values ('Foodie Paradise', '39 Anhalt Pass', 28);
insert into Restaurants (name, address, min_amt_threshold) values ('Chinese World', '110 Montana Way', 10);
insert into Restaurants (name, address, min_amt_threshold) values ('Gourmet Land', '6 Monument Circle', 14);
insert into Restaurants (name, address, min_amt_threshold) values ('Lim Eatery', '58 Mayer Junction', 16);
insert into Restaurants (name, address, min_amt_threshold) values ('Koi', '9929 School Parkway', 22);
insert into Restaurants (name, address, min_amt_threshold) values ('Llao Llao', '8 Lakeland Court', 12);
insert into Restaurants (name, address, min_amt_threshold) values ('MacDonalds', '9051 Golden Leaf Way', 20);
insert into Restaurants (name, address, min_amt_threshold) values ('Wendys', '7 Shasta Court', 28);
insert into Restaurants (name, address, min_amt_threshold) values ('Fried Chicken Specials', '85 Springs Drive', 17);
insert into Restaurants (name, address, min_amt_threshold) values ('Arnolds', '9460 Maple Wood Crossing', 16);
insert into Restaurants (name, address, min_amt_threshold) values ('Canton Paradise', '34 Dakota Terrace', 11);
insert into Restaurants (name, address, min_amt_threshold) values ('Dian Xiao Er', '36228 Golf Course Avenue', 10);
insert into Restaurants (name, address, min_amt_threshold) values ('FoodKing', '59686 Rutledge Terrace', 24);
insert into Restaurants (name, address, min_amt_threshold) values ('Pizza Place', '11904 Pleasure Pass', 28);
insert into Restaurants (name, address, min_amt_threshold) values ('Corleone Corner', '015 Thompson Crossing', 24);
insert into Restaurants (name, address, min_amt_threshold) values ('Hainan Chicken', '84674 Alpine Alley', 15);
insert into Restaurants (name, address, min_amt_threshold) values ('Laksa Mama', '9 Crownhardt Terrace', 23);
